---
title: "README"
author: "Renata"
date: "`r Sys.Date()`"
output: github_document
---

This repo houses scripts for QA of PSInet data.

## Current status

```{r, include = F, echo = F}
library(dplyr)
library(ggplot2)

tracking_data <- read.csv(here::here("dataset_tracking.csv")) |>
  select(dataset_name, latest_status) |>
  mutate(path = "template")

sfn_data  <- read.csv(here::here("sfn_to_template_tracking.csv")) |>
  select(dataset_name, status) |>
  rename(latest_status = status) |>
  mutate(path = "sfn")

tracking_data <- tracking_data |>
  bind_rows(sfn_data) |>
  mutate(latest_status = ifelse(is.na(latest_status), "submitted", latest_status))

status_key <- data.frame(
  latest_status = c('imported NO FLAGS', 'submitted', 'to template', 'to_template', 'to template with flags', 'imported WITH FLAGS'),
  status_description = c("4 - Passing QA", "2 - Ready as PSInet template", "2 - Ready as PSInet template", "2 - Ready as PSInet template", "1 - Obtained from SFN", "3 - QA flags")
)

tracking_data <- tracking_data |>
  left_join(status_key)

tracking_data_summary <- tracking_data |>
  group_by(path, status_description) |>
  tally()

theme_set(theme_bw())

```

```{r, echo = F, fig.dim = c(7,5)}

ggplot(tracking_data_summary, aes(path, n, fill = status_description)) +
  geom_col(position = "stack") +
  ggtitle("Dataset statuses"
  ) +
  xlab("Pathway") +
  ylab("Number of datasets") +
  theme(legend.position = "right") +
  scale_fill_viridis_d(option = "mako", begin = .2, end = .9, direction = -1)

knitr::kable(tracking_data_summary)

```

# Data QA instructions

TO BE UPDATED